<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "if_fluidfeed"
 *
 * Auto generated by Extension Builder 2015-01-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Interfrog Fluidfeed',
	'description' => 'Caches any given XML file via a scheduler task and transfers its contents into a fluid template.',
	'category' => 'plugin',
	'author' => '',
	'author_email' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
